# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/seb/CPP_rtype_2018

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/seb/CPP_rtype_2018

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seb/CPP_rtype_2018/CMakeFiles /home/seb/CPP_rtype_2018/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/seb/CPP_rtype_2018/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rtype

# Build rule for target.
rtype: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rtype
.PHONY : rtype

# fast build rule for target.
rtype/fast:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/build
.PHONY : rtype/fast

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/game_engine/core/Time.o: src/game_engine/core/Time.cpp.o

.PHONY : src/game_engine/core/Time.o

# target to build an object file
src/game_engine/core/Time.cpp.o:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/core/Time.cpp.o
.PHONY : src/game_engine/core/Time.cpp.o

src/game_engine/core/Time.i: src/game_engine/core/Time.cpp.i

.PHONY : src/game_engine/core/Time.i

# target to preprocess a source file
src/game_engine/core/Time.cpp.i:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/core/Time.cpp.i
.PHONY : src/game_engine/core/Time.cpp.i

src/game_engine/core/Time.s: src/game_engine/core/Time.cpp.s

.PHONY : src/game_engine/core/Time.s

# target to generate assembly for a file
src/game_engine/core/Time.cpp.s:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/core/Time.cpp.s
.PHONY : src/game_engine/core/Time.cpp.s

src/game_engine/ecs/Entity.o: src/game_engine/ecs/Entity.cpp.o

.PHONY : src/game_engine/ecs/Entity.o

# target to build an object file
src/game_engine/ecs/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/ecs/Entity.cpp.o
.PHONY : src/game_engine/ecs/Entity.cpp.o

src/game_engine/ecs/Entity.i: src/game_engine/ecs/Entity.cpp.i

.PHONY : src/game_engine/ecs/Entity.i

# target to preprocess a source file
src/game_engine/ecs/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/ecs/Entity.cpp.i
.PHONY : src/game_engine/ecs/Entity.cpp.i

src/game_engine/ecs/Entity.s: src/game_engine/ecs/Entity.cpp.s

.PHONY : src/game_engine/ecs/Entity.s

# target to generate assembly for a file
src/game_engine/ecs/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/ecs/Entity.cpp.s
.PHONY : src/game_engine/ecs/Entity.cpp.s

src/game_engine/sfml/Graphic.o: src/game_engine/sfml/Graphic.cpp.o

.PHONY : src/game_engine/sfml/Graphic.o

# target to build an object file
src/game_engine/sfml/Graphic.cpp.o:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/sfml/Graphic.cpp.o
.PHONY : src/game_engine/sfml/Graphic.cpp.o

src/game_engine/sfml/Graphic.i: src/game_engine/sfml/Graphic.cpp.i

.PHONY : src/game_engine/sfml/Graphic.i

# target to preprocess a source file
src/game_engine/sfml/Graphic.cpp.i:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/sfml/Graphic.cpp.i
.PHONY : src/game_engine/sfml/Graphic.cpp.i

src/game_engine/sfml/Graphic.s: src/game_engine/sfml/Graphic.cpp.s

.PHONY : src/game_engine/sfml/Graphic.s

# target to generate assembly for a file
src/game_engine/sfml/Graphic.cpp.s:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/sfml/Graphic.cpp.s
.PHONY : src/game_engine/sfml/Graphic.cpp.s

src/game_engine/system/control/Controls.o: src/game_engine/system/control/Controls.cpp.o

.PHONY : src/game_engine/system/control/Controls.o

# target to build an object file
src/game_engine/system/control/Controls.cpp.o:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/system/control/Controls.cpp.o
.PHONY : src/game_engine/system/control/Controls.cpp.o

src/game_engine/system/control/Controls.i: src/game_engine/system/control/Controls.cpp.i

.PHONY : src/game_engine/system/control/Controls.i

# target to preprocess a source file
src/game_engine/system/control/Controls.cpp.i:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/system/control/Controls.cpp.i
.PHONY : src/game_engine/system/control/Controls.cpp.i

src/game_engine/system/control/Controls.s: src/game_engine/system/control/Controls.cpp.s

.PHONY : src/game_engine/system/control/Controls.s

# target to generate assembly for a file
src/game_engine/system/control/Controls.cpp.s:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/system/control/Controls.cpp.s
.PHONY : src/game_engine/system/control/Controls.cpp.s

src/game_engine/system/graphical/InitAnimatedSprite.o: src/game_engine/system/graphical/InitAnimatedSprite.cpp.o

.PHONY : src/game_engine/system/graphical/InitAnimatedSprite.o

# target to build an object file
src/game_engine/system/graphical/InitAnimatedSprite.cpp.o:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/system/graphical/InitAnimatedSprite.cpp.o
.PHONY : src/game_engine/system/graphical/InitAnimatedSprite.cpp.o

src/game_engine/system/graphical/InitAnimatedSprite.i: src/game_engine/system/graphical/InitAnimatedSprite.cpp.i

.PHONY : src/game_engine/system/graphical/InitAnimatedSprite.i

# target to preprocess a source file
src/game_engine/system/graphical/InitAnimatedSprite.cpp.i:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/system/graphical/InitAnimatedSprite.cpp.i
.PHONY : src/game_engine/system/graphical/InitAnimatedSprite.cpp.i

src/game_engine/system/graphical/InitAnimatedSprite.s: src/game_engine/system/graphical/InitAnimatedSprite.cpp.s

.PHONY : src/game_engine/system/graphical/InitAnimatedSprite.s

# target to generate assembly for a file
src/game_engine/system/graphical/InitAnimatedSprite.cpp.s:
	$(MAKE) -f CMakeFiles/rtype.dir/build.make CMakeFiles/rtype.dir/src/game_engine/system/graphical/InitAnimatedSprite.cpp.s
.PHONY : src/game_engine/system/graphical/InitAnimatedSprite.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... rtype"
	@echo "... edit_cache"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/game_engine/core/Time.o"
	@echo "... src/game_engine/core/Time.i"
	@echo "... src/game_engine/core/Time.s"
	@echo "... src/game_engine/ecs/Entity.o"
	@echo "... src/game_engine/ecs/Entity.i"
	@echo "... src/game_engine/ecs/Entity.s"
	@echo "... src/game_engine/sfml/Graphic.o"
	@echo "... src/game_engine/sfml/Graphic.i"
	@echo "... src/game_engine/sfml/Graphic.s"
	@echo "... src/game_engine/system/control/Controls.o"
	@echo "... src/game_engine/system/control/Controls.i"
	@echo "... src/game_engine/system/control/Controls.s"
	@echo "... src/game_engine/system/graphical/InitAnimatedSprite.o"
	@echo "... src/game_engine/system/graphical/InitAnimatedSprite.i"
	@echo "... src/game_engine/system/graphical/InitAnimatedSprite.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

